#!/usr/bin/env python
from decimal import Decimal
from math import *

with open('input', 'r') as fin:
    s = fin.readline().rstrip()
with open('output2', 'w') as fout:
    fout.write(str(Decimal(eval(s.replace('^', '**')))))